/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as SettingsRouteRouteImport } from './pages/settings/route'
import { Route as DashboardRouteRouteImport } from './pages/dashboard/route'
import { Route as AuthRouteRouteImport } from './pages/auth/route'
import { Route as SettingsSplatRouteImport } from './pages/settings/$'
import { Route as DashboardSplatRouteImport } from './pages/dashboard/$'
import { Route as AuthSplatRouteImport } from './pages/auth/$'
import { Route as SettingswithLayoutRouteRouteImport } from './pages/settings/(with-layout)/route'
import { Route as DashboardwithLayoutRouteRouteImport } from './pages/dashboard/(with-layout)/route'
import { Route as AuthwithLayoutRouteRouteImport } from './pages/auth/(with-layout)/route'
import { Route as SettingswithLayoutSessionsRouteImport } from './pages/settings/(with-layout)/sessions'
import { Route as DashboardwithLayoutOverviewRouteImport } from './pages/dashboard/(with-layout)/overview'
import { Route as AuthwithLayoutLoginRouteImport } from './pages/auth/(with-layout)/login'

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSplatRoute = SettingsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const DashboardSplatRoute = DashboardSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthSplatRoute = AuthSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthRouteRoute,
} as any)
const SettingswithLayoutRouteRoute = SettingswithLayoutRouteRouteImport.update({
  id: '/(with-layout)',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const DashboardwithLayoutRouteRoute =
  DashboardwithLayoutRouteRouteImport.update({
    id: '/(with-layout)',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const AuthwithLayoutRouteRoute = AuthwithLayoutRouteRouteImport.update({
  id: '/(with-layout)',
  getParentRoute: () => AuthRouteRoute,
} as any)
const SettingswithLayoutSessionsRoute =
  SettingswithLayoutSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => SettingswithLayoutRouteRoute,
  } as any)
const DashboardwithLayoutOverviewRoute =
  DashboardwithLayoutOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => DashboardwithLayoutRouteRoute,
  } as any)
const AuthwithLayoutLoginRoute = AuthwithLayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthwithLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/auth/': typeof AuthwithLayoutRouteRouteWithChildren
  '/dashboard/': typeof DashboardwithLayoutRouteRouteWithChildren
  '/settings/': typeof SettingswithLayoutRouteRouteWithChildren
  '/auth/$': typeof AuthSplatRoute
  '/dashboard/$': typeof DashboardSplatRoute
  '/settings/$': typeof SettingsSplatRoute
  '/auth/login': typeof AuthwithLayoutLoginRoute
  '/dashboard/overview': typeof DashboardwithLayoutOverviewRoute
  '/settings/sessions': typeof SettingswithLayoutSessionsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthwithLayoutRouteRouteWithChildren
  '/dashboard': typeof DashboardwithLayoutRouteRouteWithChildren
  '/settings': typeof SettingswithLayoutRouteRouteWithChildren
  '/auth/$': typeof AuthSplatRoute
  '/dashboard/$': typeof DashboardSplatRoute
  '/settings/$': typeof SettingsSplatRoute
  '/auth/login': typeof AuthwithLayoutLoginRoute
  '/dashboard/overview': typeof DashboardwithLayoutOverviewRoute
  '/settings/sessions': typeof SettingswithLayoutSessionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/auth/(with-layout)': typeof AuthwithLayoutRouteRouteWithChildren
  '/dashboard/(with-layout)': typeof DashboardwithLayoutRouteRouteWithChildren
  '/settings/(with-layout)': typeof SettingswithLayoutRouteRouteWithChildren
  '/auth/$': typeof AuthSplatRoute
  '/dashboard/$': typeof DashboardSplatRoute
  '/settings/$': typeof SettingsSplatRoute
  '/auth/(with-layout)/login': typeof AuthwithLayoutLoginRoute
  '/dashboard/(with-layout)/overview': typeof DashboardwithLayoutOverviewRoute
  '/settings/(with-layout)/sessions': typeof SettingswithLayoutSessionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/dashboard'
    | '/settings'
    | '/auth/'
    | '/dashboard/'
    | '/settings/'
    | '/auth/$'
    | '/dashboard/$'
    | '/settings/$'
    | '/auth/login'
    | '/dashboard/overview'
    | '/settings/sessions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/dashboard'
    | '/settings'
    | '/auth/$'
    | '/dashboard/$'
    | '/settings/$'
    | '/auth/login'
    | '/dashboard/overview'
    | '/settings/sessions'
  id:
    | '__root__'
    | '/auth'
    | '/dashboard'
    | '/settings'
    | '/auth/(with-layout)'
    | '/dashboard/(with-layout)'
    | '/settings/(with-layout)'
    | '/auth/$'
    | '/dashboard/$'
    | '/settings/$'
    | '/auth/(with-layout)/login'
    | '/dashboard/(with-layout)/overview'
    | '/settings/(with-layout)/sessions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$': {
      id: '/settings/$'
      path: '/$'
      fullPath: '/settings/$'
      preLoaderRoute: typeof SettingsSplatRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/dashboard/$': {
      id: '/dashboard/$'
      path: '/$'
      fullPath: '/dashboard/$'
      preLoaderRoute: typeof DashboardSplatRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/$': {
      id: '/auth/$'
      path: '/$'
      fullPath: '/auth/$'
      preLoaderRoute: typeof AuthSplatRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/settings/(with-layout)': {
      id: '/settings/(with-layout)'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingswithLayoutRouteRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/dashboard/(with-layout)': {
      id: '/dashboard/(with-layout)'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardwithLayoutRouteRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/(with-layout)': {
      id: '/auth/(with-layout)'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthwithLayoutRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/settings/(with-layout)/sessions': {
      id: '/settings/(with-layout)/sessions'
      path: '/sessions'
      fullPath: '/settings/sessions'
      preLoaderRoute: typeof SettingswithLayoutSessionsRouteImport
      parentRoute: typeof SettingswithLayoutRouteRoute
    }
    '/dashboard/(with-layout)/overview': {
      id: '/dashboard/(with-layout)/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardwithLayoutOverviewRouteImport
      parentRoute: typeof DashboardwithLayoutRouteRoute
    }
    '/auth/(with-layout)/login': {
      id: '/auth/(with-layout)/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthwithLayoutLoginRouteImport
      parentRoute: typeof AuthwithLayoutRouteRoute
    }
  }
}

interface AuthwithLayoutRouteRouteChildren {
  AuthwithLayoutLoginRoute: typeof AuthwithLayoutLoginRoute
}

const AuthwithLayoutRouteRouteChildren: AuthwithLayoutRouteRouteChildren = {
  AuthwithLayoutLoginRoute: AuthwithLayoutLoginRoute,
}

const AuthwithLayoutRouteRouteWithChildren =
  AuthwithLayoutRouteRoute._addFileChildren(AuthwithLayoutRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthwithLayoutRouteRoute: typeof AuthwithLayoutRouteRouteWithChildren
  AuthSplatRoute: typeof AuthSplatRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthwithLayoutRouteRoute: AuthwithLayoutRouteRouteWithChildren,
  AuthSplatRoute: AuthSplatRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardwithLayoutRouteRouteChildren {
  DashboardwithLayoutOverviewRoute: typeof DashboardwithLayoutOverviewRoute
}

const DashboardwithLayoutRouteRouteChildren: DashboardwithLayoutRouteRouteChildren =
  {
    DashboardwithLayoutOverviewRoute: DashboardwithLayoutOverviewRoute,
  }

const DashboardwithLayoutRouteRouteWithChildren =
  DashboardwithLayoutRouteRoute._addFileChildren(
    DashboardwithLayoutRouteRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardwithLayoutRouteRoute: typeof DashboardwithLayoutRouteRouteWithChildren
  DashboardSplatRoute: typeof DashboardSplatRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardwithLayoutRouteRoute: DashboardwithLayoutRouteRouteWithChildren,
  DashboardSplatRoute: DashboardSplatRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface SettingswithLayoutRouteRouteChildren {
  SettingswithLayoutSessionsRoute: typeof SettingswithLayoutSessionsRoute
}

const SettingswithLayoutRouteRouteChildren: SettingswithLayoutRouteRouteChildren =
  {
    SettingswithLayoutSessionsRoute: SettingswithLayoutSessionsRoute,
  }

const SettingswithLayoutRouteRouteWithChildren =
  SettingswithLayoutRouteRoute._addFileChildren(
    SettingswithLayoutRouteRouteChildren,
  )

interface SettingsRouteRouteChildren {
  SettingswithLayoutRouteRoute: typeof SettingswithLayoutRouteRouteWithChildren
  SettingsSplatRoute: typeof SettingsSplatRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingswithLayoutRouteRoute: SettingswithLayoutRouteRouteWithChildren,
  SettingsSplatRoute: SettingsSplatRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
